### ISSUE TITLE
[Question] Is it possible to use a single interactive session for multiple operations?

### ISSUE THREAD

**Issue by jaehyeon-kim** [aws-samples/dbt-glue#104]
Hi

It looks that an interactive session is created for each dbt operation and it takes time to provision a new session. I wonder if it's possible to use a single interactive session for multiple operations eg) dbt debug, dbt run and dbt docs generate ...

Thanks
Jaehyeon

**Comment by pythoneerHiro** [comment]
use threads=1 @jaehyeon-kim

**Comment by moomindani** [comment]
This has been already implemented.
