### ISSUE TITLE
Java Error when building models

### ISSUE THREAD

**Issue by mattssll** [aws-samples/dbt-glue#112]
### Describe the bug
Would like to know if this issue is known and if I can get some help.
After running deploying the cloudformation set of items, and configuring the repo and running "dbt run --profiles-dir profile" the models start to build and fail. Debug runs fine. 
### Steps To Reproduce
Build the repo,
deploy the stack with cloud formation
export env vars
run: dbt run --profiles-dir profile

### Expected behavior
Models should be able to build and finish successfully 

```
### Screenshots and log output
```
    '''), Py4JError: An error occurred while calling o91.toString. Trace:
18:25:24    java.lang.IllegalArgumentException: object is not an instance of declaring class
18:25:24        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
18:25:24        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
18:25:24        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
18:25:24        at java.lang.reflect.Method.invoke(Method.java:498)
18:25:24        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
18:25:24        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
18:25:24        at py4j.Gateway.invoke(Gateway.java:282)
18:25:24        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
18:25:24        at py4j.commands.CallCommand.execute(CallCommand.java:79)
18:25:24        at py4j.GatewayConnection.run(GatewayConnection.java:238)
18:25:24        at java.lang.Thread.run(Thread.java:750)
18:25:24    
18:25:24    
18:25:24    compiled Code at target/run/dbtgluenyctaxidemo/models/silver_metrics/silver_nyctaxi_avg_metrics.sql
### System information
**The output of `dbt --version`:**
```
Core:
  - installed: 1.3.0
  - latest:    1.3.0 - Up to date!

Plugins:
  - spark: 1.3.0 - Up to date!
```

**The operating system you're using:**
Macos

**The output of `python --version`:**
Python 3.8.9

### Additional context
Just wondering if you guys have seen this error before.

**Comment by nicor88** [comment]
Have a look at this https://github.com/aws-samples/dbt-glue/issues/77 could be that you have missing iam permissions. Try to use glue 2.0, as requires less permissions, if you use 3.0 use the glue issue linked above to see what you you need to add, specifically I found out that glue:GetUserDefinedFunctions was missing in the set of iam actions

**Comment by mattssll** [comment]
cool, thanks, I'll be closing this one as it's the same as #77  - thanks @nicor88

**Comment by jacksbox** [comment]
I would like to reopen this topic as I ran into the same issue when using glue 4.0

Error message with glue 4.0. This gives me no clear hint of what is going on.

```
Database Error in model stg_source (models/staging/stg_source.sql)
  Glue cursor returned `error` for statement None for code SqlWrapper2.execute('''/* {"app": "dbt", "dbt_version": "1.9.4", "profile_name": "cellforce_dbt_glue", "target_name": "dev", "node_id": "model.cellforce_dbt_glue.stg_source"} */
  drop table if exists limslabguruexperiments_dev_silver_db.stg_source''', use_arrow=False, location='None'), Py4JError: An error occurred while calling o89.toString. Trace:
  java.lang.IllegalArgumentException: object is not an instance of declaring class
  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.lang.reflect.Method.invoke(Method.java:498)
  	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
  	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
  	at py4j.Gateway.invoke(Gateway.java:282)
  	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
  	at py4j.commands.CallCommand.execute(CallCommand.java:79)
  	at py4j.GatewayConnection.run(GatewayConnection.java:238)
  	at java.lang.Thread.run(Thread.java:750)
```

Error message with glue 2.0. This helped me solve the issue.

```
Database Error in model stg_source (models/staging/stg_source.sql)
  Glue cursor returned `error` for statement None for code SqlWrapper2.execute('''/* {"app": "dbt", "dbt_version": "1.9.4", "profile_name": "cellforce_dbt_glue", "target_name": "dev", "node_id": "model.cellforce_dbt_glue.stg_source"} */
  drop table if exists limslabguruexperiments_dev_silver_db.stg_source''', use_arrow=False, location='None'), AnalysisException: 'java.lang.RuntimeException: MetaException(message:Unable to verify existence of default database: com.amazonaws.services.glue.model.AccessDeniedException: User: *** is not authorized to perform: glue:GetDatabase on resource: *** because no identity-based policy allows the glue:GetDatabase action (Service: AWSGlue; Status Code: 400; Error Code: AccessDeniedException; Request ID: ***; Proxy: null));'
```
