### ISSUE TITLE
Merge - second run creates duplicates

### ISSUE THREAD

**Issue by pixie79** [aws-samples/dbt-glue#118]
### Describe the bug
Starting with a new model where the incremental mode is set to merge if the same data is loaded again then duplicates are loaded.

### Steps To Reproduce
I have been playing with the settings and think we have found a bug with the merge logic
(if we are doing it correctly, and a small workaround)

Here is a sample repo with a simple model and a csv of test data - https://github.com/pixie79/dbt_glue_merge/blob/main/models/refined/customer_test.sql

What we have found is that if we just run the model, then it correctly creates the new table with the appropriate data. If we then rerun the model (either a full refresh or an incremental that also has some previous data caught in) which we would do to ensure at least once processing. Instead of merging the duplicated record it inserts new duplicated rows of data. If you run a third time you might expect to get a third duplicate but oddly you don't.

### Workaround (or potential fix option)
Now for the work around, whilst with DBT you can not create an empty table it seems that if we update the model to have "limit 1" as the last line, then run it. It creates the table with one record in as expected. Then remove the limit 1 and rerun with either incremental or full refresh and it correctly loads all the data. At this point we expected the initial row to be duplicated but it was not (we have no idea why not). Again if you do another run the data is fine.
Just to point out so far we have not validated this is changing data only replaying exactly the same data (hence really there should be no duplicate).

### Expected behavior
Second run of the same data to allow only once processing merge should either re-update the original record or not touch it as a duplicate.

### System information
**The output of `dbt --version`:**
```
poetry run dbt --version                       
The currently activated Python version 3.9.15 is not supported by the project (>=3.10,<3.11).
Trying to find and use a compatible version. 
Using python3 (3.10.8)
Core:
  - installed: 1.3.1
  - latest:    1.3.1 - Up to date!

Plugins:
  - redshift: 1.3.0 - Up to date!
  - postgres: 1.3.1 - Up to date!
  - spark:    1.3.0 - Up to date!

```

**Comment by moomindani** [comment]
Incremental mode with `merge` strategy is supported only in hudi or iceberg. 
Standard formats like csv will cause duplicates when doing incremental merge.
