### ISSUE TITLE
Support for most recent software versions of Iceberg Connectors from AWS Marketplace

### ISSUE THREAD

**Issue by mehdimld** [aws-samples/dbt-glue#134]
### Describe the feature
Support more recent/any version of the Iceberg Connector from AWS Marketplace.

### Additional context
As a result of the #132 merge, the Iceberg incremental materialization has been re-designed. This implies that Iceberg Connectors from AWS Marketplace more recent than the Software version 0.12.0-2 (Feb 14, 2022) are no longer supported (they were in the previous Iceberg 'Table' materialization).  

### Are you interested in contributing this feature?
Yes

**Comment by moomindani** [comment]
Currently the most recent version of Iceberg marketplace connector is 1.2.1. (Built-in adapter is 1.0.0).
It is managed in Glue service, not in the dbt-glue adapter. Resolving.
