### ISSUE TITLE
Build your data pipeline in your AWS modern data platform using AWS Lake Formation, AWS Glue, and dbt Core

### ISSUE THREAD

**Issue by NancyWu007** [aws-samples/dbt-glue#148]
There seems lost one s in the section Clean up step 2. Delete all generated data:

$ aws s3 rm s3://aws-dbt-glue-datalake-$(aws sts get-caller-identity --query "Account" --output text)-us-east-1/ --recursive
$ aws s3 rm 3://aws-athena-dbt-glue-query-results-$(aws sts get-caller-identity --query "Account" --output text)-us-east-1/ --recursive

Suggested version:
$ aws s3 rm s3://aws-dbt-glue-datalake-$(aws sts get-caller-identity --query "Account" --output text)-us-east-1/ --recursive
_$ aws s3 rm s3://aws-athena-dbt-glue-query-results-$(aws sts get-caller-identity --query "Account" --output text)-us-east-1/ --recursive_

**Comment by moomindani** [comment]
Thank you for the feedback. We fixed it in the post: https://aws.amazon.com/blogs/big-data/build-your-data-pipeline-in-your-aws-modern-data-platform-using-aws-lake-formation-aws-glue-and-dbt-core/
