### ISSUE TITLE
Glue Interactive Session times out after 13-15 minutes of dbt-run

### ISSUE THREAD

**Issue by nandubatchu** [aws-samples/dbt-glue#157]
### Describe the bug
A clear and concise description of what the bug is. What command did you run? What happened?
Everytime I run my dbt - the jobs run perfectly fine upto 13-15 minutes and any job post that fails with a session timeout error as given below.

### Steps To Reproduce
In as much detail as possible, please provide steps to reproduce the issue. Sample data that triggers the issue, example model code, etc is all very helpful here.

- Setup a dbt repo with dbt-glue adapater 
- Add multiple jobs which can cover the 15 minute window
- Run the dbt (should see the command start failing for the jobs post 13-15 minutes)

### Expected behavior

- I should be able to run dbt for N number of jobs in sequence (single thread) without any time limit (beyond 15 minutes)

### Screenshots and log output
If applicable, add screenshots or log output to help explain your problem.

```
01:20:05  33 of 69 OK created sql incremental model <REDACTED> [OK in 20.87s]
01:20:05  34 of 69 START sql incremental model <REDACTED> .. [RUN]
01:20:33  34 of 69 OK created sql incremental model <REDACTED>  [OK in 28.54s]
01:20:33  35 of 69 START sql incremental model <REDACTED>  [RUN]
01:20:46  Glue adapter: Error in GlueCursor execute An error occurred (InvalidInputException) when calling the GetStatement operation: Session is not ready, session_id=GlueInteractiveSessionRole-dbt-glue-72f17828-41b6-42e8-beec-5ff6f2a5cf31, status=TIMEOUT
01:20:46  Glue adapter: __init__() missing 3 required positional arguments: 'cwd', 'cmd', and 'message'
01:20:46  Glue adapter: Error in GlueCursor execute An error occurred (InvalidInputException) when calling the RunStatement operation: Session is not ready, session_id=GlueInteractiveSessionRole-dbt-glue-72f17828-41b6-42e8-beec-5ff6f2a5cf31, status=TIMEOUT
01:20:46  35 of 69 ERROR creating sql incremental model <REDACTED>  [ERROR in 12.94s]
01:20:46  36 of 69 START sql incremental model <REDACTED>  [RUN]
01:20:47  Glue adapter: Error in GlueCursor execute An error occurred (InvalidInputException) when calling the RunStatement operation: Session is not ready, session_id=GlueInteractiveSessionRole-dbt-glue-72f17828-41b6-42e8-beec-5ff6f2a5cf31, status=TIMEOUT
01:20:47  Glue adapter: Got an error when attempting to open a GlueSession : __init__() missing 2 required positional arguments: 'cmd' and 'message'
01:20:47  36 of 69 ERROR creating sql incremental model <REDACTED>  [ERROR in 0.92s]
01:20:47  37 of 69 START sql incremental model <REDACTED> . [RUN]
```

### System information
**The output of `dbt --version`:**
```
Core:
  - installed: 1.3.2
  - latest:    1.4.5 - Update available!

  Your version of dbt-core is out of date!
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation

Plugins:
  - glue:  1.3.12 - Up to date!
  - spark: 1.3.1  - Update available!

  At least one plugin is out of date or incompatible with dbt-core.
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation
```

**The operating system you're using:**
Linux (Gitpod)

**The output of `python --version`:**
```
Python 3.8.16
```

### Additional context

I am using dbt-glue to transform my Apache HUDI tables stored on S3

**Comment by adithyapathipaka** [comment]
@nandubatchu , what was timeout set in dbt profile? As you every job is terminating after 15 mins, please check glue session timeout.

**Comment by nandubatchu** [comment]
@adithyapathipaka which config are you referring to?
```
idle_timeout = 5 (custom)
query_timeout_in_seconds = 300 (default)
session_provisioning_timeout_in_seconds = 180 (custom)
```

**Comment by adithyapathipaka** [comment]
Yes. I am referring the idle_timeout. Please set value based on the you max query execution time.

**Comment by snazki** [comment]
Thank You @adithyapathipaka! @nandubatchu and me were stuck with this problem for a while and your response helped us get unblocked. Appreciate your help!!
