### ISSUE TITLE
Does dbt-glue work with an encrypted S3 bucket?

### ISSUE THREAD

**Issue by pwrstar** [aws-samples/dbt-glue#169]
I'm trying to use dbt-glue adapter and facing `Service: Amazon S3; Status Code: 403; Error Code: AccessDenied` Error. I have specified the security-configuration which we usually provide in our glue job but it doesn't seem to work. 

Can you tell me if this dbt-glue adapter is able to pass on the configuration or if this is some kind of limitation you have currently for dbt-glue?

Thanks!

**Comment by AmineIzanami** [comment]
@pwrstar dbt-glue create a glue interactive session with the Service role "role_arn" in the profile.yml, can you review the permissions of that IAM Role, and are you using lake formation ?
