### ISSUE TITLE
Error when dbt run with incremental model and strategy is 'insert_overwrite' with version `1.5.0`

### ISSUE THREAD

**Issue by binhnq94** [aws-samples/dbt-glue#192]
### Describe the bug

I got error when `dbt run --models <my_model>` with newest version `1.5.0` but it run will with old version `dbt-glue==1.4.23`
My model is incremental model and strategy is 'insert_overwrite'.

### Steps To Reproduce
In as much detail as possible, please provide steps to reproduce the issue. Sample data that triggers the issue, example model code, etc is all very helpful here.

### Expected behavior

Got none error.

### Screenshots and log output

```
12:03:22  Running with dbt=1.5.2
12:03:23  Registered adapter: glue=1.5.0
12:03:23  Unable to do partial parsing because config vars, config profile, or config target have changed
12:03:23  Found 6 models, 27 tests, 0 snapshots, 0 analyses, 508 macros, 0 operations, 0 seed files, 4 sources, 0 exposures, 0 metrics, 0 groups
12:03:23  
12:03:25  Concurrency: 1 threads (target='dev')
12:03:25  
12:03:25  1 of 1 START sql incremental model my_schema.my_model ...... [RUN]
12:07:13  Glue adapter: 'NoneType' object is not iterable
12:07:16  Glue adapter: Glue returned `error` for statement None for code SqlWrapper2.execute('''/* {"app": "dbt", "dbt_version": "1.5.2", "profile_name": "my_profile", "target_name": "dev", "node_id": "model.my_project.my_model"} */

    set hive.exec.dynamic.partition.mode=nonstrict
    dbt_next_query
    insert overwrite table my_schema.my_model
    partition (created_date)
    select  from my_schema.my_model_tmp
'''), ParseException: 
mismatched input '.' expecting {<EOF>, ';'}(line 4, pos 27)

== SQL ==

    insert overwrite table my_schema.my_model
    partition (created_date)
    select  from my_schema.my_model_tmp
---------------------------^^^

12:07:16  1 of 1 ERROR creating sql incremental model my_schema.my_model  [ERROR in 231.39s]
12:07:34  
12:07:34  Finished running 1 incremental model in 0 hours 4 minutes and 11.10 seconds (251.10s).
12:07:34  
12:07:34  Completed with 1 error and 0 warnings:
12:07:34  
12:07:34  Database Error in model my_model (models/my_sub_folder/my_model.sql)
12:07:34    Glue cursor returned `error` for statement None for code SqlWrapper2.execute('''/* {"app": "dbt", "dbt_version": "1.5.2", "profile_name": "my_profile", "target_name": "dev", "node_id": "model.my_project.my_model"} */
12:07:34    
12:07:34        set hive.exec.dynamic.partition.mode=nonstrict
12:07:34        dbt_next_query
12:07:34        insert overwrite table my_schema.my_model
12:07:34        partition (created_date)
12:07:34        select  from my_schema.my_model_tmp
12:07:34    '''), ParseException: 
12:07:34    mismatched input '.' expecting {<EOF>, ';'}(line 4, pos 27)
12:07:34    
12:07:34    == SQL ==
12:07:34    
12:07:34        insert overwrite table my_schema.my_model
12:07:34        partition (created_date)
12:07:34        select  from my_schema.my_model_tmp
12:07:34    ---------------------------^^^
12:07:34    
12:07:34    compiled Code at target/run/my_project/models/my_sub_folder/my_model.sql
12:07:34  
12:07:34  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
```

### System information
**The output of `dbt --version`:**
```
Core:
  - installed: 1.5.2
  - latest:    1.5.2 - Up to date!

Plugins:
  - glue:  1.5.0 - Up to date!
  - spark: 1.5.0 - Up to date!

```

**The operating system you're using:** I used the docker image: apache/airflow:2.6.2-python3.10

**The output of `python --version`: ** Python 3.10.11

**Comment by menuetb** [comment]
I fixed this issue in version 1.5.2

**Comment by binhnq94** [comment]
@menuetb It will got error if the order of columns is different between my_model_tmp and my_model.
The error log example:
```
INFO - - Cannot safely cast 'first_column': date to int
INFO - - Cannot safely cast 'second_column': int to timestamp
INFO - - Cannot safely cast 'third_column': string to int
INFO - - Cannot safely cast 'fourth_column': string to int
INFO - - Cannot safely cast 'fifth_columns': bigint to date
```

**Comment by binhnq94** [comment]
@menuetb Another concern, why `adapter.get_columns_in_relation(source_relation)` return null columns since 1.5.0 version?

**Comment by rishabh1815769** [comment]
> @menuetb It will got error if the order of columns is different between my_model_tmp and my_model. The error log example:
> 
> ```
> INFO - - Cannot safely cast 'first_column': date to int
> INFO - - Cannot safely cast 'second_column': int to timestamp
> INFO - - Cannot safely cast 'third_column': string to int
> INFO - - Cannot safely cast 'fourth_column': string to int
> INFO - - Cannot safely cast 'fifth_columns': bigint to date
> ```
> 
> It is lucky because error `Cannot saftely cast` raised, because if the wrong order between `source_relation` and `target_relation` will lead to save wrong data. It is possible to save data of column X to columns Y in case 2 columns have the same type.

Hi @binhnq94 , I am also getting the same error. Did you manage to solve this error? If would be really helpful for me if you could help me out here. Thank you in advance !

**Comment by binhnq94** [comment]
@rishabh1815769 I have a quick solution: rearrage columns in SQL to fit the `target_relation`.
@menuetb Do you have other solution?

**Comment by rishabh1815769** [comment]
> 

@binhnq94 got it ! Thanks for the solution I will try to implement it and let you know.
