### ISSUE TITLE
Stop Session gets called indefinitely

### ISSUE THREAD

**Issue by sanga8** [aws-samples/dbt-glue#248]
### Describe the bug
For unknown reason, the session does not seem to stop. Had to stop the session manually. See the time stamps on the following screenshots. 
<img width="966" alt="Capture d’écran 2023-10-24 à 18 00 22" src="https://github.com/aws-samples/dbt-glue/assets/38979776/528a576d-8e11-426f-aa56-485c42524f39">

<img width="968" alt="Capture d’écran 2023-10-24 à 18 00 29" src="https://github.com/aws-samples/dbt-glue/assets/38979776/f624a766-8142-4079-9fd2-8bc57f9dabd1">

This issue has been encountered by other users, see the discussion in the [slack channel](https://getdbt.slack.com/archives/C02R4HSMBAT/p1696480901378129):

### Expected behavior
The session stops.

### System information
dbt-glue:1.6.5
python:3.9.11

**Comment by TwDme** [comment]
Same here, following

**Comment by menuetb** [comment]
Can you upgrade dbt-glue adapter, we have just release a version fixing this issue with dbt-glue:1.6.6.
