### ISSUE TITLE
Incremental append appears broken with latest version

### ISSUE THREAD

**Issue by sanga8** [aws-samples/dbt-glue#307]
### Describe the bug
The incremental append appears to have been broken with latest changes

### Steps To Reproduce
1/ Launch a table with following config

{{
    config(
        materialized='incremental',
        incremental_strategy='append'
    )
}}
SELECT a, b
FROM db.table_source

2/ Add a new line to your table_source, relaunch model.
You should have the following error:

insert into table dbt_skeleton_project.glue_incremental_append
select  from dbt_skeleton_project.glue_incremental_append_tmp
ParseException: 
  Syntax error at or near '.'(line 4, pos 37)

Turns out there's no columns after the select.
The bug was introduced with 1.7.1, it is working fine in 1.7.0

### Adapter version
```
dbt-glue==1.7.1
```

**Comment by moomindani** [comment]
This has been fixed.
