### ISSUE TITLE
CloudFormation Python Version

### ISSUE THREAD

**Issue by CyCodeDev** [aws-samples/dbt-glue#399]
Not directly a dbt code issue, but related.

Referencing the instructions here: https://aws.amazon.com/blogs/big-data/build-and-manage-your-modern-data-stack-using-dbt-and-aws-glue-through-dbt-glue-the-new-trusted-dbt-adapter/

The CloudFormation template rollback is caused by an old dependency on Python 3.7 within CreatePartitionsFunction. This function should be updated by default to a later version of Python 3.12.

**Comment by moomindani** [comment]
Thanks for the feedback.
I have updated the CloudFormation template to upgrade Python version from 3.7 to 3.12.
