### ISSUE TITLE
Airflow example

### ISSUE THREAD

**Issue by whrocha** [aws-samples/dbt-glue#41]
It will be nice if we have and example of how to use it integrated with airflow.

**Comment by menuetb** [comment]
We will have a look at this.
For now, in AWS, for automation we have a template for AWS batch (using Redshift adapter) describe in that blog post: https://aws.amazon.com/blogs/big-data/automating-deployment-of-amazon-redshift-etl-jobs-with-aws-codebuild-aws-batch-and-dbt/

**Comment by mmehrten** [comment]
I don't know if this is needed - `dbt-glue` just allows dbt to run on Glue, so the existing dbt documentation for dbt and Airflow should be sufficient for this use case IMO. Here are some good resources to check out:

* https://www.getdbt.com/blog/dbt-airflow/
* https://airflow.apache.org/docs/apache-airflow-providers-dbt-cloud/stable/operators.html
* https://github.com/gocardless/airflow-dbt
* https://docs.astronomer.io/learn/airflow-dbt
* https://www.datafold.com/blog/running-dbt-with-airflow

@whrocha are there `dbt-glue` specific callouts you think we should include wrt Airflow integration?

**Comment by menuetb** [comment]
We have published a doc to use dbt with MWAA: https://docs.aws.amazon.com/mwaa/latest/userguide/samples-dbt.html
