### ISSUE TITLE
Link in README.md points to a non-existing file

### ISSUE THREAD

**Issue by vilhomaa** [aws-samples/dbt-glue#474]
### Describe the bug
In the documentation, in the section

```
Configuring tables
When materializing a model as table, you may include several optional configs that are specific to the dbt-spark plugin, 
in addition to the standard [model configs](https://github.com/aws-samples/dbt-glue/blob/main/model-configs).
```
The link https://github.com/aws-samples/dbt-glue/blob/main/model-configs in "model configs" does not seem to exist

**Comment by moomindani** [comment]
Thanks for reporting it. Just removed the link.
https://github.com/aws-samples/dbt-glue/commit/f3f3f1ab7061544e5d4a6557a2903d39692b9a52
