### ISSUE TITLE
1.8.7

### ISSUE THREAD

**Issue by sanga8** [aws-samples/dbt-glue#477]

**Comment by sanga8** [comment]
Hello @moomindani ! When do you think we could be able to release a new version including the latest changes ?

**Comment by moomindani** [comment]
Thanks for bringing this up.
We will be able to do that around mid December, but let me know if it does not work.

**Comment by sanga8** [comment]
We're looking at deploying some projects in UAT/PROD it would be great if we can have it a bit earlier :)
I can help if there's anything you need to check before the release

**Comment by aiss93** [comment]
Hi @moomindani,
We have the same need on my side :) 
Thank you

**Comment by moomindani** [comment]
I understand the needs of this. The current timing is bit tricky for us due to AWS re:Invent, and I have zero capacity on managing this release right now. In my earliest timing, I will try to address this around December 12. Apologizes for delay.

**Comment by sanga8** [comment]
Understood, thank you @moomindani !

**Comment by moomindani** [comment]
Now we have published dbt-glue 1.9.0 including Glue 5.0 by default.
Thank you all for the contributions!

* https://github.com/aws-samples/dbt-glue/releases/tag/1.9.0
* https://test.pypi.org/project/dbt-glue/1.9.0/
* https://test.pypi.org/project/dbt-glue/1.9.0/
