### ISSUE TITLE
Error when running models at second time (materialized='table')

### ISSUE THREAD

**Issue by teslahenry** [aws-samples/dbt-glue#48]
### Describe the bug
I try to run the models with the following [this tutorial](https://aws.amazon.com/blogs/big-data/build-your-data-pipeline-in-your-aws-modern-data-platform-using-aws-lake-formation-aws-glue-and-dbt-core/). It's successful at the first time, but failed when I run it again

### Steps To Reproduce
1. Following [this tutorial](https://aws.amazon.com/blogs/big-data/build-your-data-pipeline-in-your-aws-modern-data-platform-using-aws-lake-formation-aws-glue-and-dbt-core/)
2. Run the command `dbt run --profiles-dir profile` in terminal
3. Run the command again --> Failed.

### Expected behavior
The job should be successful and the tables will be re-created.

### Screenshots and log output
Error message as below:
```
(dbt_venv) [cloudshell-user@ip-10-0-73-218 dbtgluenyctaxidemo]$ dbt run --profiles-dir profile
16:00:47  Running with dbt=1.1.1
16:00:47  Found 4 models, 0 tests, 0 snapshots, 0 analyses, 225 macros, 0 operations, 0 seed files, 1 source, 0 exposures, 0 metrics
16:00:47  
16:02:19  Concurrency: 1 threads (target='dev')
16:02:19  
16:02:19  1 of 4 START table model dbt_nyc_metrics.silver_nyctaxi_avg_metrics ............ [RUN]
16:02:22  Unhandled error while executing model.dbtgluenyctaxidemo.silver_nyctaxi_avg_metrics
Field "type" of type Optional[RelationType] in SparkRelation has invalid value Undefined
16:02:22  1 of 4 ERROR creating table model dbt_nyc_metrics.silver_nyctaxi_avg_metrics ... [ERROR in 2.09s]
16:02:22  2 of 4 SKIP relation dbt_nyc_metrics.gold_nyctaxi_cost_metrics ................. [SKIP]
16:02:22  3 of 4 SKIP relation dbt_nyc_metrics.gold_nyctaxi_distance_metrics ............. [SKIP]
16:02:22  4 of 4 SKIP relation dbt_nyc_metrics.gold_nyctaxi_passengers_metrics ........... [SKIP]
16:02:24  
16:02:24  Finished running 4 table models in 96.53s.
16:02:24  
16:02:24  Completed with 1 error and 0 warnings:
16:02:24  
16:02:24  Field "type" of type Optional[RelationType] in SparkRelation has invalid value Undefined
16:02:24  
16:02:24  Done. PASS=0 WARN=0 ERROR=1 SKIP=3 TOTAL=4
```
### System information
**The output of `dbt --version`:**
```
Core:
  - installed: 1.1.1
  - latest:    1.1.1 - Up to date!

Plugins:
  - spark: 1.1.0 - Up to date!
  - spark: 1.1.0 - Up to date!
```

**The operating system you're using:** AWS ClouShell
**The output of `python --version`:** Python 3.7.10

**Comment by ericsalesdeandrade** [comment]
Hey, 
I have an error on the same tutorial running it on CloudShell. Followed all the steps exactly but have the error
```
Glue adapter: Glue returned `error` for statement None for code SqlWrapper2.execute('''show databases'''), Py4JError: An error occurred while calling o82.toString. Trace:
java.lang.IllegalArgumentException: object is not an instance of declaring class
```
![Screenshot 2022-07-11 at 13 23 42](https://user-images.githubusercontent.com/95698321/178332220-2e17525a-8b4b-44aa-81bb-4974e061b2d0.png)

**Comment by menuetb** [comment]
I changed the show databases statement by a boto3 call.
The permissions with Glue 3 also changed, I updated the Cfn template to deploy, but it's not yet deployed in the blog post.
To make it works, please add this policy to the `GlueInteractiveSessionRole` IAM Role:
`
{
            "Action": [
                "glue:GetUserDefinedFunctions"
            ],
            "Resource": [
                "*"
            ],
            "Effect": "Allow"
        },
`
I just give it a try and it works on my side:
![image](https://user-images.githubusercontent.com/83284881/178472222-55722e7d-5ad1-4313-96a1-325918a9d775.png)

**Comment by ericsalesdeandrade** [comment]
Thank you @menuetb so much. This worked beautifully on CloudShell. 

I've been trying the same example locally and while the DBT runs successfully, it generates blank tables. Been struggling to figure out what's wrong. The only thing I changed is the region, deployed to `eu-west-2`. Compared logs with CloudShell but can't seem to find the issue. 

Any suggestions?
