### ISSUE TITLE
Delta Lake Support for DBT Glue

### ISSUE THREAD

**Issue by adithyapathipaka** [aws-samples/dbt-glue#51]
Do dbt-glue support delta lake base load? I am trying to transform data using delta lake but failing at save.

**Comment by menuetb** [comment]
Hi, I just developed a beta version which now support Delta Lake.
You can install this beta using the following command:
`python3 -m pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ dbt-glue`

You can find the documentation for the configuration here:
https://github.com/aws-samples/dbt-glue/blob/delta_lake_integration/README.md#delta

You need to install delta glue connectors to make it works, here is the doc for that:
https://docs.aws.amazon.com/glue/latest/ug/connectors-chapter.html

**Comment by menuetb** [comment]
The version of the dbt adapter with delta lake support is now published.
