### ISSUE TITLE
spark.driver.maxResultSize default to 1 Gb after HUDI non-partition load

### ISSUE THREAD

**Issue by armaseg** [aws-samples/dbt-glue#67]
### Describe the feature
Be able to modify the parameter spark.driver.maxResultSize that currently default is 1 Gb after HUDI non-partition load

### Are you interested in contributing this feature?
Yes

**Comment by moomindani** [comment]
Spark configurations like `spark.driver.maxResultSize` can be passed through `conf`.
Since we do not need to set this default, closing this issue.
