### ISSUE TITLE
No output on all models on S3 when dbt threads is greater than 1

### ISSUE THREAD

**Issue by armaseg** [aws-samples/dbt-glue#70]
### Describe the bug
When we configure more than one thread on the profile.yml, dbt runs and says that everything is OK, nevertheless there is no output on S3 on all models

### Steps To Reproduce
Clean the output folders of your dbt project, then set your threads greater than 1 (ex: 3 (recommended value by dbt to start a project)), run your project and check the output on S3     
```
workers: 3
worker_type: G.2X
threads: 3
```

### Expected behavior
All output files written

### System information
**The output of `dbt --version`:**
```
Core:
  - installed: 1.2.1
  - latest:    1.2.1 - Up to date!
  Plugins:
  - spark: 1.2.0 - Up to date!
dbt-glue 0.2.6
```

**The operating system you're using:**
macos

**The output of `python --version`:**
Python 3.7.13

**Comment by jgensler8** [comment]
fwiw, I am seeing a similar issue though I am using only 1 worker. I do get expected results when using 1 thread, so maybe that can be used to unblock in the meantime. Using 2 threads results in some missing tables (with dbt runs marked as OK). I believe that a reproducible example can be made using any type of models that can be created at the same time. In my case, I have one parent and two dependencies:

```
# a.sql
select * from {{ ref('parent') }} where a
# b.sql
select * from {{ ref('parent') }} where b
```

with 2 threads + if a finishes before b, a's table will be missing. 

<details>
  <summary>runtime config / dbt --version </summary>

```
glue_version: "3.0"
worker_type: Standard
```

```
Core:
  - installed: 1.3.0
  - latest:    1.3.0 - Up to date!

Plugins:
  - spark:    1.3.0 - Up to date!
```
</details>

**Comment by SiddyP** [comment]
Also seeing this issue when increasing the thread count

**Comment by nandubatchu** [comment]
is someone checking on this? can this be tagged as a bug? what workarounds are suggested meanwhile?

**Comment by nandubatchu** [comment]
@armaseg - does this adapter support threads? Is there any workaround suggested if it does not support?

**Comment by armaseg** [comment]
Hello @nandubatchu , For the moment is not supported and we don't have any workaround. I worked on that issue a long time ago but I didn't finish it and then I jumped to another one that was more urgent.

**Comment by nandubatchu** [comment]
It takes a humongous amount of time without threads. Can this be a priority now? For someone to pick?

**Comment by nandubatchu** [comment]
@armaseg waiting for your reply!
