### ISSUE TITLE
Glue Interactive sessions are not being stopped

### ISSUE THREAD

**Issue by armaseg** [aws-samples/dbt-glue#95]
### Describe the bug
I ran a dbt project and the session didn't stop at the end of the run. It timed out thanks to the configuration on the profile, but it didn't stop.
 
### Steps To Reproduce
Run a project until it finishes.
Go to the AWS console -> Glue -> Interactive Sessions and you will see that your session is ready and then it will change status to Timeout

### Expected behavior
dbt-glue should stop the Glue Interactive session at the end of the run 
 
### Screenshots and log output
If applicable, add screenshots or log output to help explain your problem.
![image](https://user-images.githubusercontent.com/1028859/196684569-60728790-f0d7-49c9-8797-2df209ca1934.png)

### System information
**The output of `dbt --version`:**
```
Core:
  - installed: 1.2.2
```

**Comment by armaseg** [comment]
Dropping issue. It was related to a development issue

**Comment by pythoneerHiro** [comment]
@armaseg  What was the development issue

**Comment by armaseg** [comment]
Hello @pythoneerHiro,
While doing my development, I removed a try-catch by accident. I then tested again on the published version and everything was OK. Sorry for the inconvenience

**Comment by pythoneerHiro** [comment]
@armaseg where did you use "try-catch" in pythonic models or in a separate glue notebook using the same role?

**Comment by armaseg** [comment]
none of them, I was working on a new feature on this [file](https://github.com/aws-samples/dbt-glue/blob/main/dbt/adapters/glue/gluedbapi/connection.py) and I didn't notice that I removed a try- except: 
Sorry for the misunderstanding
